Repository ss14-ganimed/Ganimed-main, pull requests merged in 2023-06, with the labels that each got.

#2 Плюшки и ручки
  Resources/Locale/ru-RU/Ganimed/pens.ftl
  Resources/Locale/ru-RU/Ganimed/toys.ftl
  Resources/Prototypes/Entities/Objects/Devices/pda.yml
  Resources/Prototypes/Ganimed/Entities/Objects/pens.yml
  Resources/Prototypes/Ganimed/Entities/Objects/toys.yml
  Resources/Textures/Ganimed/Objects/pens.rsi/RnD_pen.png
  Resources/Textures/Ganimed/Objects/pens.rsi/agent_pen.png
  Resources/Textures/Ganimed/Objects/pens.rsi/blue_pen.png
  Resources/Textures/Ganimed/Objects/pens.rsi/cargo_pen.png
  Resources/Textures/Ganimed/Objects/pens.rsi/ce_pen.png
  Resources/Textures/Ganimed/Objects/pens.rsi/chem_pen.png
  Resources/Textures/Ganimed/Objects/pens.rsi/cmo_pen.png
  Resources/Textures/Ganimed/Objects/pens.rsi/eng_pen.png
  Resources/Textures/Ganimed/Objects/pens.rsi/fish_pen.png
  Resources/Textures/Ganimed/Objects/pens.rsi/green_pen.png
  Resources/Textures/Ganimed/Objects/pens.rsi/hos_pen.png
  Resources/Textures/Ganimed/Objects/pens.rsi/love_pen.png
  Resources/Textures/Ganimed/Objects/pens.rsi/med_pen.png
  Resources/Textures/Ganimed/Objects/pens.rsi/meta.json
  Resources/Textures/Ganimed/Objects/pens.rsi/pink_pen.png
  Resources/Textures/Ganimed/Objects/pens.rsi/purple_pen.png
  Resources/Textures/Ganimed/Objects/pens.rsi/qm_pen.png
  Resources/Textures/Ganimed/Objects/pens.rsi/rainbow_pen.png
  Resources/Textures/Ganimed/Objects/pens.rsi/rd_pen.png
  Resources/Textures/Ganimed/Objects/pens.rsi/sec_pen.png
  Resources/Textures/Ganimed/Objects/pens.rsi/space_pen.png
  Resources/Textures/Ganimed/Objects/pens.rsi/yellow_pen.png
  Resources/Textures/Ganimed/Objects/plushies.rsi/ave.png
  Resources/Textures/Ganimed/Objects/plushies.rsi/calisto.png
  Resources/Textures/Ganimed/Objects/plushies.rsi/erhard.png
  Resources/Textures/Ganimed/Objects/plushies.rsi/graff.png
  Resources/Textures/Ganimed/Objects/plushies.rsi/kiss_1.png
  Resources/Textures/Ganimed/Objects/plushies.rsi/kiss_2.png
  Resources/Textures/Ganimed/Objects/plushies.rsi/mensk.png
  Resources/Textures/Ganimed/Objects/plushies.rsi/meta.json
  Resources/Textures/Ganimed/Objects/plushies.rsi/mira.png
  Resources/Textures/Ganimed/Objects/plushies.rsi/morgan.png
  Resources/Textures/Ganimed/Objects/plushies.rsi/qm.png
Labels: Размер: Маленький, Приоритет: 3 - Средний, Без C#, Изменено: Спрайты, Изменено: Переводы

#12 Обновлено время для открытия ролей
  Resources/Prototypes/Corvax/Roles/Jobs/Engineering/chief_engineer.yml
  Resources/Prototypes/Corvax/Roles/Jobs/Wildcards/psychologist.yml
  Resources/Prototypes/Roles/Jobs/Cargo/cargo_technician.yml
  Resources/Prototypes/Roles/Jobs/Cargo/quartermaster.yml
  Resources/Prototypes/Roles/Jobs/Cargo/salvage_specialist.yml
  Resources/Prototypes/Roles/Jobs/Civilian/chef.yml
  Resources/Prototypes/Roles/Jobs/Civilian/clown.yml
  Resources/Prototypes/Roles/Jobs/Command/captain.yml
  Resources/Prototypes/Roles/Jobs/Command/head_of_personnel.yml
  Resources/Prototypes/Roles/Jobs/Engineering/atmospheric_technician.yml
  Resources/Prototypes/Roles/Jobs/Engineering/station_engineer.yml
  Resources/Prototypes/Roles/Jobs/Engineering/technical_assistant.yml
  Resources/Prototypes/Roles/Jobs/Medical/chemist.yml
  Resources/Prototypes/Roles/Jobs/Medical/chief_medical_officer.yml
  Resources/Prototypes/Roles/Jobs/Medical/medical_doctor.yml
  Resources/Prototypes/Roles/Jobs/Medical/medical_intern.yml
  Resources/Prototypes/Roles/Jobs/Medical/paramedic.yml
  Resources/Prototypes/Roles/Jobs/Science/research_assistant.yml
  Resources/Prototypes/Roles/Jobs/Science/research_director.yml
  Resources/Prototypes/Roles/Jobs/Science/scientist.yml
  Resources/Prototypes/Roles/Jobs/Security/detective.yml
  Resources/Prototypes/Roles/Jobs/Security/head_of_security.yml
  Resources/Prototypes/Roles/Jobs/Security/security_cadet.yml
  Resources/Prototypes/Roles/Jobs/Security/security_officer.yml
  Resources/Prototypes/Roles/Jobs/Security/warden.yml
Labels: Размер: Средний, Приоритет: 1 - Неотложный, Без C#

#21 Перенос консоли криминальных записей
  Content.Client/CriminalRecords/GeneralCriminalRecordConsoleBoundUserInterface — копия.cs
  Content.Client/CriminalRecords/GeneralCriminalRecordConsoleWindow.xaml
  Content.Client/CriminalRecords/GeneralCriminalRecordConsoleWindow.xaml.cs
  Content.Server/CriminalRecords/Components/GeneralCriminalRecordConsoleComponent.cs
  Content.Server/CriminalRecords/Systems/CriminalRecordsSystem.cs
  Content.Server/CriminalRecords/Systems/GeneralCriminalRecordConsoleSystem.cs
  Content.Server/Security/Components/SecurityInfoComponent.cs
  Content.Shared/CriminalRecords/GeneralCriminalRecord.cs
  Content.Shared/CriminalRecords/SharedGeneralCriminalRecordConsoleSystem.cs
  Content.Shared/Security/SecurityStatus.cs
  Content.Shared/StationRecords/GeneralStationRecord.cs
  Resources/Locale/ru-RU/criminal-records/general-criminal-records.ftl
  Resources/Prototypes/Entities/Mobs/Species/base.yml
  Resources/Prototypes/Entities/Structures/Machines/Computers/computers.yml
Labels: Статус: Нуждается в рассмотрении, Размер: Средний, Приоритет: 3 - Средний, Изменено: UI

#18 Unlock
  Resources/Prototypes/Corvax/Entities/Mobs/Customization/Markings/cat_parts.yml
  Resources/Prototypes/Entities/Mobs/Customization/Markings/cat_parts.yml
Labels: Тип: Требуется тестирование, Статус: Ожидает изменений, Размер: Маленький, Приоритет: 3 - Средний, Без C#
