Repository ss14-ganimed/Ganimed-main, pull requests merged in 2023-07, with the labels that each got.

#30 Исправлены права для накрутки времени
  Content.Server/Administration/Commands/PlayTimeCommands.cs
Labels: Размер: Маленький, Приоритет: 2 - Высокий

#27 Общая частота СБ и гарнитуры
  Resources/Locale/ru-RU/Ganimed/radio_chanels.ftl
  Resources/Locale/ru-RU/ss14-ru/prototypes/entities/objects/devices/encryption_keys.ftl
  Resources/Prototypes/Entities/Clothing/Ears/headsets.yml
  Resources/Prototypes/Entities/Clothing/Ears/headsets_alt.yml
  Resources/Prototypes/Entities/Objects/Devices/encryption_keys.yml
  Resources/Prototypes/radio_channels.yml
Labels: Размер: Маленький, Требуется: Другой PR, Приоритет: 3 - Средний, Без C#, Изменено: Переводы

#31 Доработка изменений гарнитур, ключей шифрования и каналов связи
  Resources/Locale/ru-RU/Ganimed/headsets.ftl
  Resources/Locale/ru-RU/Ganimed/radio_channels.ftl
  Resources/Locale/ru-RU/ss14-ru/prototypes/entities/clothing/ears/headsets_alt.ftl
  Resources/Locale/ru-RU/ss14-ru/prototypes/entities/objects/devices/encryption_keys.ftl
  Resources/Prototypes/Entities/Clothing/Ears/headsets.yml
  Resources/Prototypes/Entities/Clothing/Ears/headsets_alt.yml
  Resources/Prototypes/Entities/Objects/Devices/encryption_keys.yml
  Resources/Prototypes/Roles/Jobs/Fun/emergencyresponseteam.yml
  Resources/Prototypes/Roles/Jobs/Fun/misc_startinggear.yml
  Resources/Prototypes/radio_channels.yml
  Resources/Textures/Ganimed/Clothing/headset_black.rsi/alt-equipped-EARS.png
  Resources/Textures/Ganimed/Clothing/headset_black.rsi/equipped-EARS.png
  Resources/Textures/Ganimed/Clothing/headset_black.rsi/icon.png
  Resources/Textures/Ganimed/Clothing/headset_black.rsi/icon_alt.png
  Resources/Textures/Ganimed/Clothing/headset_black.rsi/meta.json
  Resources/Textures/Objects/Devices/encryption_keys.rsi/crypt_black.png
  Resources/Textures/Objects/Devices/encryption_keys.rsi/crypt_green.png
  Resources/Textures/Objects/Devices/encryption_keys.rsi/meta.json
Labels: Статус: Нуждается в рассмотрении, Размер: Средний, Требуется: Другой PR, Приоритет: 3 - Средний, Без C#, Изменено: Спрайты, Изменено: Переводы

#32 Ивент с зомби может начаться только от 20 человек
  Resources/Prototypes/GameRules/events.yml
Labels: Тип: Баланс, Размер: Маленький, Приоритет: 3 - Средний, Без C#

#38 добавлены наниты и их инъекторы
  Resources/Locale/ru-RU/Ganimed/nanites_injector.ftl
  Resources/Locale/ru-RU/Ganimed/nanomachines.ftl
  Resources/Prototypes/Ganimed/Entities/Objects/medical/nanites_injectors.yml
  Resources/Prototypes/Reagents/nanomachines_son.yml
Labels: Размер: Средний, Приоритет: 2 - Высокий, Без C#, Изменено: Переводы

#39 Арахниды в стойло
  Resources/Prototypes/Species/arachnid.yml
Labels: Размер: Маленький, Приоритет: 1 - Неотложный, Без C#

#33 ребаланс скафандров, в том числе и глав
  Resources/Prototypes/Entities/Clothing/OuterClothing/hardsuits.yml
Labels: Тип: Баланс, Размер: Маленький, Приоритет: 3 - Средний, Без C#

#40 Снят лимит по изучениям технологий в РНД
  Content.Shared/Research/Components/TechnologyDatabaseComponent.cs
  Content.Shared/Research/Systems/SharedResearchSystem.cs
Labels: Размер: Маленький, Приоритет: 2 - Высокий, Без C#

#46 Добавление перчаток Крав Мага
  Resources/Locale/ru-RU/ss14-ru/prototypes/entities/clothing/hands/gloves.ftl
  Resources/Prototypes/Catalog/Fills/Lockers/security.yml
  Resources/Prototypes/Entities/Clothing/Hands/gloves.yml
  Resources/Prototypes/Objectives/traitorObjectives.yml
  Resources/Textures/Clothing/Hands/Gloves/krav.rsi/equipped-HAND.png
  Resources/Textures/Clothing/Hands/Gloves/krav.rsi/icon.png
  Resources/Textures/Clothing/Hands/Gloves/krav.rsi/inhand-left.png
  Resources/Textures/Clothing/Hands/Gloves/krav.rsi/inhand-right.png
  Resources/Textures/Clothing/Hands/Gloves/krav.rsi/meta.json
Labels: Размер: Маленький, Приоритет: 2 - Высокий, Без C#, Изменено: Спрайты, Изменено: Переводы

#41 Добавление нанитов для парамедика и СМО, а так-же для медика ОБР
  Resources/Prototypes/Catalog/Fills/Lockers/heads.yml
  Resources/Prototypes/Roles/Jobs/Fun/emergencyresponseteam.yml
  Resources/Prototypes/Roles/Jobs/Medical/paramedic.yml
Labels: Размер: Маленький, Приоритет: 3 - Средний, Без C#

#42 кнопка наблюдать в чате у гостов
  Content.Client/UserInterface/Systems/Chat/Widgets/ChatBox.xaml.cs
  Content.Server/Ganimed/Commands/OrbitCommand.cs
Labels: Размер: Маленький, Приоритет: 4 - Низкий, Изменено: UI
